### ISSUE TITLE
Printing Labels does not seem to work

### ISSUE THREAD

**Issue by ebartz** [exteso/alf.io-PI#40]
Hi there,

I have a problem getting badge printing to work. I have a Dymo LabelWriter 450 turbo which you suggest in your great tutorial.

I Installed everything as described and also checked that the printer works. It is installed in Cups and I can even print the cups test page. Whenever I click on Print in the frontend to reprint badged, just nothing happens and nothing appears in the logs.

Any idea, where I could search for the issues?

**Comment by cbellone** [comment]
Hi @ebartz !

Please note that Alf.io-PI does not work (yet) on linux distributions other than Raspbian Stretch. The latest Raspbian is not yet supported.

That being said, can you please post the content of the `/dev/usb` folder? 
You should have a device named Alfio-DYM-{SERIAL-NUMBER}

if you don't find anything, unplug and plug again the printer, then check the output of `dmesg`

**Comment by ebartz** [comment]
HI @cbellone ,

I followed the instructions on alf.io to install everything. There you link directly to the strech release which I installed:

OS Release:
```
root@raspberrypi:~# cat /etc/*ase
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
lsusb:
```
root@raspberrypi:~# lsusb
Bus 001 Device 004: ID 1eab:0003
Bus 001 Device 005: ID 0922:0021 Dymo-CoStar Corp.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
ls /dev/usb/
```
root@raspberrypi:~# ls -lah /dev/usb/
insgesamt 0
drwxr-xr-x  2 root root     80 Jun 14 20:28 .
drwxr-xr-x 15 root root   3,4K Jun 14 20:28 ..
lrwxrwxrwx  1 root root      3 Jun 14 20:28 Alfio-DYM-1E4F1Z5 -> lp0
crw-rw----  1 root lp   180, 0 Jun 14 20:28 lp0
```

Also Cups shows that the printer is working just fine:

![image](https://user-images.githubusercontent.com/6342767/84627923-094e6600-aee8-11ea-9731-7f27388fa2d3.png)

And when I print something via CUPS that works just fine so I think the printer is connected correctly and works just fine.

Package Version:
```
root@raspberrypi:~# dpkg -l | grep alf
ii  alf.io-pi                             0.9.9-1                           all          alf.io-pi
```

For some reason I had problems with the installation of the openjdk which I fixed by purging the package and reinstalling it. Also this step of the install script failed:
https://github.com/alfio-event/alf.io-PI/blob/bf84ae7190dbbaf266f324d46ead96062c07ce9b/backend/etc/get-alfio-pi.sh#L73
Therefore I just skipped it and everything starts now.

**Comment by cbellone** [comment]
thank you very much for the detailed answer.

> For some reason I had problems with the installation of the openjdk which I fixed by purging the package and reinstalling it

yes, we're aware of it. It's totally random. Sometimes it works, sometimes not. I think that there's something wrong with the java9 package. 
Anyway we should solve it once we migrate to Raspbian Buster. Any help with the testing/migration would be highly appreciated


> Also this step of the install script failed:

thanks for reporting this. It looks like that the deb file has been signed using an expired key. We'll release a new version asap.

Back to the printer-specific issue: sometimes the printer doesn't get recognized when the LW450 is already plugged in on startup. Can you please try to start the RPi and connect the printer once the system is up and running?

You can see if the printer has been recognized by following this procedure:

- connect the printer
- wait 10 seconds
- tap on the "Settings" menu
- if the printer has been recognized, you should see: `Label Printing on Alfio-DYM-1E4F1Z5` on screen

**Comment by ebartz** [comment]
I did everything you wanted. Booted without the printer and connected it after everything was up and running. 

And also disconnected and reconnected it a few time but it still does not work.

Is there anything I can do to increase the logging? Because I don't see any errors so far.

**Comment by ebartz** [comment]
If it helps I cloud also give you SSH Access to the raspberry or arrange a zoom session or whatever helps you to find out whats going wrong :)

**Comment by cbellone** [comment]
thanks :+1: 

I am working on a new release to fix the problem with the expired signature. Will also add some extra "trace" logs

btw you should already be able to increase the logging by adding the following line:
`logging.level.alfio=TRACE`

in your `/home/pi/.config/alf.io/application.properties`

**Comment by cbellone** [comment]
OK, I have released [v0.9.10](https://github.com/alfio-event/alf.io-PI/releases/tag/v0.9.10)

can you please install it?

once installed, please enable trace logs
`logging.level.alfio=TRACE`
in your `/home/pi/.config/alf.io/application.properties`

and then restart the PI. Let's see if we can understand what's happening :-)

thank you very much for your help. Really appreciated!

**Comment by ebartz** [comment]
I tried increasing the log but actually whenever I click on "Print" just nothing happens in the logs. I think I will just start with a complete reinstall of the system just to sort out that something went wrong during the installation. 

Do you suggest connecting the printer before the installation or should I wait until the system is completely installed and started?

**Comment by ebartz** [comment]
Soooo I guess something went wrong with discovering the printer?

```
2020-06-17 14:56:17.580 TRACE 454 --- [qtp21007811-15] alfio.ScanLogManager                     : PrinterId is not defined, trying to find default for user desk-user
2020-06-17 14:56:17.607 TRACE 454 --- [qtp21007811-15] alfio.ScanLogManager                     : Printer found: false
2020-06-17 14:56:17.611 TRACE 454 --- [qtp21007811-15] alfio.ScanLogManager                     : Detected desk user. Trying to find a local printer
2020-06-17 14:56:17.649 TRACE 454 --- [qtp21007811-15] alfio.pi.manager.PrintManager            : Processing output from lpstat: Drucker Alfio-DYM-1E4F1Z5 ist im Leerlauf.  Aktiviert seit Mo 15 Jun 2020 12:54:08 UTC
2020-06-17 14:56:17.650 TRACE 454 --- [qtp21007811-15] alfio.pi.manager.PrintManager            : --> Printer name is: null
```

And by the way, the rest of the upgrade went smooth. But it seems like on every upgrade it is overwriting the whole configuration and data of already scanned tickets?

**Comment by cbellone** [comment]
I think we have a winner here

```
2020-06-17 14:56:17.649 TRACE 454 --- [qtp21007811-15] alfio.pi.manager.PrintManager            : Processing output from lpstat: Drucker Alfio-DYM-1E4F1Z5 ist im Leerlauf.  Aktiviert seit Mo 15 Jun 2020 12:54:08 UTC
2020-06-17 14:56:17.650 TRACE 454 --- [qtp21007811-15] alfio.pi.manager.PrintManager            : --> Printer name is: null
```

Ich glaube, dass der Alf.io kann nicht Deutsch verstehen :-)

jokes aside, the regular expression we use to extract the printer name expects the output of lpstat to be in English. 

`printer (Alfio\S+) .*`

this is actually naive, and I think we could safely replace the fixed string "printer" with a more generic matching. 
In the meantime, can you please switch the OS language to English (US), so that you can confirm that everything is working well?

> But it seems like on every upgrade it is overwriting the whole configuration and data of already scanned tickets?

no, just this time. Sorry.
From now on, the system will use the API-Key as key for encrypting the database file on-disk and for communicating with the other nodes in the cluster, if any.
This was a long-standing breaking change that we had in mind, and I took the opportunity to include it in the new release.

**Comment by ebartz** [comment]
Okay - so that makes sense in a way. And yep - it works after changing the default language.

To get the printers, you can also check the cups config files:

Search for the printers in /etc/cups/printers.conf
``` bash
grep -oP '(?<=<Printer ).*?(?=>)'  /etc/cups/printers.conf
```

I think changing the regex to ` (Alfio\S+) .*` should also work for all languages. I don't know if there if it always begins with Alfio-? If so , maybe use ` (Alfio-\S+) .*`

**Comment by ebartz** [comment]
Ok... now that I got printing to work, there seems to be another printing related issue:

https://youtu.be/TI45qigoS58

This is unusual, right? The printer is the Dymo LabelWriter 450 Turbo. The used labels are 41mm x 89mm which I got directly from amazon:

https://www.amazon.de/gp/product/B00095MQ94/

Is it again me doing something wrong?

**Comment by cbellone** [comment]
> Okay - so that makes sense in a way. And yep - it works after changing the default language.
> 
> To get the printers, you can also check the cups config files:
> 
> Search for the printers in /etc/cups/printers.conf
> 
> ```shell
> grep -oP '(?<=<Printer ).*?(?=>)'  /etc/cups/printers.conf
> ```

thanks for the suggestion. Will try to parse the printer.conf file

> 
> I think changing the regex to ` (Alfio\S+) .*` should also work for all languages. I don't know if there if it always begins with Alfio-? If so , maybe use ` (Alfio-\S+) .*`

Yes, because we configure all the supported printers when they're plugged in, through a set of custom udev rules. See
https://github.com/alfio-event/alf.io-PI/blob/0.9-maintenance/backend/deb/resources/etc/udev/rules.d/99-alfio.rules#L1


> Ok... now that I got printing to work, there seems to be another printing related issue:
> https://youtu.be/TI45qigoS58
> This is unusual, right? The printer is the Dymo LabelWriter 450 Turbo. The used labels are 41mm x 89mm which I got directly from amazon:
> https://www.amazon.de/gp/product/B00095MQ94/
> Is it again me doing something wrong?

ouch, that's weird. Thanks for the video. The labels are the right ones.

This usually happens when you print 6-7 labels without removing them and they somehow jam the motor, because it's not powerful enough to push their weight. 

The usual process is to print one label at a time, then remove it and stick it to the badge. This gives enough slack (2-3s) to the printer to reset. This does not apply to Zebra printers, as they're much faster.

I have some questions:

- Did you buy the LW450T recently? (I'm wondering if there could be issues with the driver version we use)
- Does `dmesg` show anything unusual?

I would try the following:
- check that the Raspberry PI has enough power. From what I can see from the video, this should not be the issue, but better check
- change the USB port
- try to print the label directly
[label.pdf](https://github.com/alfio-event/alf.io-PI/files/4794794/label.pdf)
using the following command
`/usr/bin/lpr -U anonymous -P test-label -# 1 -T ticket-test -h -o media=w118h252 label.pdf`

**Comment by ebartz** [comment]
I just got the printer and everything else new last week.

Power should be ok, there are no low power warnings and the power-supply is capable of supplying up to 4A which should be more than enough.

When I print the pdf labels the printer shows the same behavior as I showed in the video.
whenever I start a print job, dmesg showed this:
```
[  +8,393840] usblp0: removed
[ +12,258081] usblp 1-1.5:1.0: usblp0: USB Bidirectional printer dev 7 if 0 alt 0 proto 2 vid 0x0922 pid 0x0021
```
After I saw those messages I changed the power connection from the raspberry to be directly connected to the display which now powers the PI over the GPIO pins.

Dmesg messages are gone. Printer still does not work correctly. I printed about 100 labels now and I would say every 3rd is a fail which then generates 2 blank labels before printing a correct label again.

I can't figure out what exactly causes this behavior and I can't find any kind of firmware upgrade. Maybe I should just swap the Dymo for a Zebra printer.

**Comment by cbellone** [comment]
I am afraid that the DYMO is not the right tool for the job, if your goal is to print labels in rapid succession. 
We were thinking of adding a "bulk mode scan" for this, so that you can scan multiple tickets, and only after send all the pages to the printer in a single job. 

Otherwise, for a classic check-in scenario, the DYMO would do just fine. We have printed up to 750 labels in 1.5h on a single printer while people showed up at a crowded conference. 
We had to clean the printing head from time to time, because it gets dirt quickly, but we haven't had any other issues.

Have you already tried to reproduce the issue on another CUPS-powered computer? (Mac OS or Linux). Just to make sure that the printer is not defective...

another thing you can try is to disable usblp temporarily:

`sudo /sbin/rmmod usblp` 

and see if this solves the issue.

we disable usblp automatically when you plug in a Zebra printer, because this increases the printing speed. 
I'm not sure it can also help with the LW450T, but I think it's worth a try.

**Comment by ebartz** [comment]
I mean I am not planning to print as many labels as you described. The only thing I need is a setup which is reliable. And currently the printer gets stuck and does waste a a big amount of labels. I also saw that the Zebra labels are much  cheaper compared to the Dymo ones.

I tried to use the printer also with on my mac and the behavior is basically the same. So maybe its just a bad unit that I got. Will try to get a replacement. And besides that I just ordered the Zebra just to try things out.

Thank verry much for the great support. You guys built something really awesome here.

By the way, are you open for paid features? I think if we decide to go with alf, we will need a couple of things and I would have to decide whether we try to code them or just pay you guys to get them.

**Comment by cbellone** [comment]
> Thank verry much for the great support. You guys built something really awesome here.

thanks, really appreciated

> By the way, are you open for paid features? I think if we decide to go with alf, we will need a couple of things and I would have to decide whether we try to code them or just pay you guys to get them.

yes we are. We've developed "sponsored" features in the past, your company logo will appear as a sponsor. Invoicing is done through [Swicket](https://swicket.io)

**Comment by ebartz** [comment]
Just for your information. I got a replacement for the Dymo and the new unit works just fine. Thanks again for your support and for making this awesome peace of software :)
